return {
	"lua_ls",
	"bashls",
	"cssls",
	cssmodules_ls = { disable = true },
	unocss = { disable = true },
	eslint = { disable = false },
	"emmet_ls",
	"html",
	"jsonls",
	tsserver = { disable = true },
	tailwindcss = { disable = true },
	"volar",
	"stylelint_lsp",
	"yamlls",
	"marksman",
	"gopls",
	"dockerls",
}
